version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne --bind 0.0.0.0:8000 core.asgi:application"
            
    volumes:
      - .:/app
      - static_data:/app/staticfiles  # Mount the volume for static files
      - media_data:/app/media        # Mount the volume for media files
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
    - db  
    expose:
      - "8000"  # Expose port 8000 internally for Nginx to communicate with

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose port 80 on the host to port 80 in the container (for external access)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx config
      - static_data:/app/staticfiles  # Ensure static files are served by Nginx
      - media_data:/app/media   # Ensure media files are served by Nginx
    depends_on:
      - web
    restart: always    

volumes:
  static_data:  # Declare static data volume
    driver: local
  media_data:  # Declare media data volume
    driver: local
  postgres_data:  # Declare PostgreSQL volume
    driver: local  
