version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 lms.wsgi:application"
    volumes:
      - .:/app
      - static_data:/app/staticfiles  # Mount the volume for static files
      - media_data:/app/media        # Mount the volume for media files
    environment:
      - DJANGO_SETTINGS_MODULE=lms.settings
    expose:
      - "8000"  # Expose port 8000 internally for Nginx to communicate with

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose port 80 on the host to port 80 in the container (for external access)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx config
      - static_data:/usr/share/nginx/html/static  # Ensure static files are served by Nginx
      - media_data:/usr/share/nginx/html/media   # Ensure media files are served by Nginx
    depends_on:
      - web

volumes:
  static_data:  # Declare static data volume
    driver: local
  media_data:  # Declare media data volume
    driver: local
