version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 lms.wsgi:application"
    volumes:
      - .:/app
      - static_data:/app/staticfiles  # Store static files in a shared volume
      - media_data:/app/media        # Store media files in a shared volume
    ports:
      - "80:8000"  # Expose port 8000 for Django app
    environment:
      - DJANGO_SETTINGS_MODULE=lms.settings
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/usr/share/nginx/html/static
      - media_data:/usr/share/nginx/html/media
    depends_on:
      - web    

volumes:
  postgres_data:
    driver: local
  static_data:  # Declare static data volume
    driver: local
  media_data:  # Declare media data volume
    driver: local
