# Generated by Django 5.1.3 on 2024-12-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
    ]
