# Generated by Django 5.1.3 on 2024-11-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnHub', '0004_alter_menuitem_childrens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='childrens',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='LearnHub.menuitem'),
        ),
    ]
